name: Iroha2 JSON schema updating workflow
#on:
#  repository_dispatch:
#    types: [update-schema]
on:
  push:
    branches: [feature/iroha-171/schema-update-workflow]
jobs:
  update-schema:
    runs-on: ubuntu-latest
    env:
      SCHEMA_FILE_PATH: modules/codegen/src/main/resources
    steps:
      - uses: actions/checkout@v2
        with:
          ref: iroha2-dev
      - name: Calculate current schema file hash
        run: echo "::set-output name=SCHEMA_FILE_HASH::$(sha256sum $SCHEMA_FILE_PATH/schema.json | awk '{print $1}')"
        id: current-schema-hash
      - name: Abort if schema wasn't updated
        if: ${{ github.event.client_payload.schemaHash == steps.current-schema-hash.outputs.SCHEMA_FILE_HASH }}
        run: exit 0
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: feature/auto-update-schema
      - name: Download schema artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: iroha2-dev-send-schema-to-client.yml
          workflow_conclusion: success
          branch: iroha2-dev-schema-to-client
          name: schema
          path: ${{env.SCHEMA_FILE_PATH}}
          repo: arndey/iroha
      - name: Generate models by new schema with Gradle
        run: ./gradlew generate
      - name: Update JSON schema
        uses: test-room-7/action-update-file@v1
        with:
          file-path: ${{ env.SCHEMA_FILE_PATH }}/schema.json
          commit-msg: (automatic commit) JSON schema updated
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: feature/auto-update-schema
      - name: Update generated models
        uses: test-room-7/action-update-file@v1
        with:
          file-path: modules/model/src/main/kotlin/jp/co/soramitsu/iroha2/generated/**/*.kt
          commit-msg: (automatic commit) generated models updated
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: feature/auto-update-schema
      - name: Create PR
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: (automatic) JSON schema update
          body: >
            This PR is auto-generated.
            New schema file hash ${{ github.event.client_payload.schemaHash }}
          labels: automated pr
          branch: feature/auto-update-schema
          signoff: true
          delete-branch: true
          base: iroha2-dev
          reviewers: arndey